import { IProduct } from "./Types";

export const products: IProduct[] = [
  {
    id: 1,
    title: "Biryani",
    image: "",
    slug: "/biryani",
    price: 20,
    category: "Meal",
    description: "The love of every foodie ",
    flavors: ["Chicken", "Mutton", "Beef"],
    topping: ["Salad", "Raita", "Extra Meat"],
    quantity: ["1/2kg", "1kg"],
    discount: "10%",
    Reviews: ["best biryani i tasted", "i want to come for more"],
    Rating: 5,
    Availability: true,
  },
  {
    id: 2,
    title: "Tikka",
    image: "",
    slug: "/tikka",
    price: 20,
    category: "BBQ",
    description: "The love of every BBQ lover ",
    flavors: ["Chicken", "Mutton", "Beef"],
    topping: ["Salad", "Raita", "Extra Meat", "Cheese"],
    quantity: ["1/2pcs", "fullpcs"],
    discount: "5%",
    Reviews: ["best tikka i tasted", "i want to come for more"],
    Rating: 5,
    Availability: true,
  },
  {
    id: 3,
    title: "Soup",
    image: "",
    slug: "/soup",
    price: 20,
    category: "Meal",
    description: "The love of every foodie ",
    flavors: ["Chicken", "Mutton", "Beef"],
    topping: ["Salad", "Raita", "Extra Meat"],
    quantity: ["1/2kg", "1kg"],
    discount: "10%",
    Reviews: ["best biryani i tasted", "i want to come for more"],
    Rating: 5,
    Availability: true,
  },
  {
    id: 4,
    title: "Chai/Tea",
    image: "",
    slug: "/chai",
    price: 20,
    category: "BBQ",
    description: "The love of every BBQ lover ",
    flavors: ["Chicken", "Mutton", "Beef"],
    topping: ["Salad", "Raita", "Extra Meat", "Cheese"],
    quantity: ["1/2pcs", "fullpcs"],
    discount: "5%",
    Reviews: ["best tikka i tasted", "i want to come for more"],
    Rating: 5,
    Availability: true,
  },
];
