import { IBlog } from "./Types";

export const mockBlogs: IBlog[] = [
    {
      id: 1,
      title: "The Ultimate Guide to React",
      slug: "ultimate-guide-to-react",
      content: "React is a JavaScript library for building user interfaces. It is maintained by Facebook and a community of individual developers and companies...",
      summary: "Learn the basics of React, including components, state, and props.",
      author: "John Doe",
      image: "/images/react-guide.jpg",
      tags: ["React", "JavaScript", "Web Development"],
      category: "Programming",
      createdAt: "2025-01-01T10:00:00Z",
      updatedAt: "2025-01-05T15:00:00Z",
      isPublished: true,
      comments: [
        {
          id: 1,
          user: "Jane Smith",
          message: "Great article! It really helped me understand React.",
          createdAt: "2025-01-02T08:30:00Z",
        },
        {
          id: 2,
          user: "Mike Lee",
          message: "I love how you explained the lifecycle methods!",
          createdAt: "2025-01-03T12:00:00Z",
        },
      ],
    },
    {
      id: 2,
      title: "10 Tips for Effective Blogging",
      slug: "10-tips-for-effective-blogging",
      content: "Blogging is a great way to share your ideas and expertise. To make your blog more effective, consider these tips: 1. Write for your audience...",
      summary: "Discover tips to make your blogging journey more impactful and enjoyable.",
      author: "Sarah Connor",
      image: "/images/blogging-tips.jpg",
      tags: ["Blogging", "Writing", "Content Creation"],
      category: "Writing",
      createdAt: "2025-01-10T14:00:00Z",
      isPublished: true,
      comments: [
        {
          id: 1,
          user: "Alex Turner",
          message: "Thanks for the tips! I implemented them, and my blog engagement increased.",
          createdAt: "2025-01-12T10:00:00Z",
        },
      ],
    },
    {
      id: 3,
      title: "Understanding Node.js",
      slug: "understanding-nodejs",
      content: "Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser...",
      summary: "Learn what Node.js is, how it works, and why it’s so popular in backend development.",
      author: "Michael Brown",
      image: "/images/nodejs-guide.jpg",
      tags: ["Node.js", "Backend", "JavaScript"],
      category: "Programming",
      createdAt: "2025-01-15T11:00:00Z",
      isPublished: true,
      comments: [
        {
          id: 1,
          user: "Linda Harris",
          message: "Node.js is amazing, and your article explained it so well!",
          createdAt: "2025-01-16T13:30:00Z",
        },
      ],
    },
    {
      id: 4,
      title: "The Benefits of Yoga",
      slug: "benefits-of-yoga",
      content: "Yoga is not just a form of exercise but a way to improve your mental and physical well-being. Regular yoga practice can enhance flexibility, strength, and mindfulness...",
      summary: "Discover how yoga can transform your life and improve your well-being.",
      author: "Emily Johnson",
      image: "/images/yoga-benefits.jpg",
      tags: ["Yoga", "Health", "Wellness"],
      category: "Health",
      createdAt: "2025-01-18T09:00:00Z",
      isPublished: false,
      comments: [],
    },
    {
      id: 5,
      title: "Traveling on a Budget",
      slug: "traveling-on-a-budget",
      content: "Traveling doesn’t have to be expensive. With the right strategies, you can explore the world without breaking the bank. Start by planning your trip in advance...",
      summary: "Learn how to travel the world without spending a fortune.",
      author: "Anna Clark",
      image: "/images/travel-budget.jpg",
      tags: ["Travel", "Budgeting", "Adventure"],
      category: "Travel",
      createdAt: "2025-01-20T08:00:00Z",
      isPublished: true,
      comments: [
        {
          id: 1,
          user: "Tom Baker",
          message: "This is exactly what I needed before my next trip. Thanks!",
          createdAt: "2025-01-21T11:00:00Z",
        },
      ],
    },
  ];
  